source("util.r")
source("data.r")
source("minority.r")
source("score.r")
source("boost.r")
source("test.r")

summary_candidate_stats <- summary_stats()
write.csv(summary_candidate_stats, "out/candidate.csv")
summary_voter_stats <- voter_stats()
write.csv(summary_voter_stats, "out/voter.csv")
